# Generated by Django 2.1.2 on 2018-11-04 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('discription', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='docs/')),
            ],
        ),
    ]
